export type OfferKitPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: number;
  views: number;
  image: string;
  tags: string[];
  content: string;
};

export const posts: OfferKitPost[] = [
  {
    slug: "8-week-placement-prep-roadmap",
    title: "The 8-week placement prep roadmap that actually fits college life",
    excerpt: "A practical weekly plan for balancing classes, coding practice, projects, and applications without burning out.",
    category: "Roadmaps",
    date: "2026-09-04",
    readTime: 7,
    views: 1248,
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    tags: ["roadmap", "planning", "placements"],
    content: `Placement preparation feels impossible when every senior gives you a different checklist. The fix is not another giant list. It is a sequence that protects your attention and gives each week one clear job.\n\nWeeks 1 and 2 are for your baseline. Pick one target role, take a timed aptitude set, solve five easy and medium DSA problems, and write down the CS subjects you can explain without opening notes. Do not judge the score yet. You are collecting evidence. At the same time, update your resume with measurable project outcomes and create a simple tracker for applications, referrals, and follow-ups.\n\nWeeks 3 and 4 are your fundamentals sprint. Spend four days each week on DSA patterns: arrays and hashing, two pointers, stacks and queues, binary search, and trees. On the fifth day, revise DBMS, operating systems, and computer networks using questions rather than passive reading. A 45-minute recall session beats three hours of highlighting. Keep one evening free for college work and rest; consistency needs space.\n\nWeeks 5 and 6 are for proof. Build or polish one project you can demo in two minutes. Prepare a README, architecture sketch, and three trade-offs you made. Start mixed timed sets so you practise switching from aptitude to coding to theory. Ask a friend to conduct one technical mock interview. After it, write down every moment where your answer became vague. Those moments are your next revision list.\n\nWeek 7 is interview simulation. Do two complete practice loops: an online assessment, a technical round, and a short HR conversation. Practise saying your thought process out loud. Recruiters are evaluating how you handle uncertainty, not only whether you remember a trick. Make a one-page story bank with examples for teamwork, conflict, ownership, failure, and learning.\n\nWeek 8 is a taper, not a panic sprint. Revisit your error log, sleep on a regular schedule, and prepare questions for each company. Keep solving one small problem daily, but stop collecting new resources. Before each interview, review the job description and connect two of your projects to the role.\n\nThe roadmap works because it turns preparation into repeatable blocks. You will still have bad days and surprise assignments. Restart at the next block instead of declaring the whole plan broken. The goal is not to feel ready every morning; it is to keep becoming easier to shortlist and easier to trust.`,
  },
  {
    slug: "ats-friendly-resume",
    title: "How to build an ATS-friendly resume that still sounds like you",
    excerpt: "Make your resume readable to screening software and useful to the human who opens it next.",
    category: "Resume",
    date: "2026-08-28",
    readTime: 6,
    views: 987,
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    tags: ["resume", "ATS", "applications"],
    content: `An ATS-friendly resume is not a document stuffed with keywords. It is a clear argument: this student has practised the skills in the job description and can show the work. A good resume helps software find the right terms, then helps a recruiter understand your contribution in seconds.\n\nStart with a plain structure. Use one column, familiar headings, and readable text. Keep your name, phone, email, LinkedIn, GitHub, education, skills, projects, experience, and achievements in a predictable order. Avoid text boxes, multi-column templates, decorative icons, skill bars, and information hidden in headers or footers. They may look clever but can be parsed badly.\n\nMatch language honestly. If a role asks for Java, SQL, REST APIs, or debugging, use the same terms when they describe work you have actually done. Do not create a keyword wall in the skills section. Put important words inside proof: “Built a Java service that reduced duplicate records by 28%” is stronger than “Java, backend, problem solving.” Read the job description once for nouns and once for verbs, then reflect the most relevant ones in your bullets.\n\nWrite bullets with action, scope, and result. “Created a college event app used by 400 students; added role-based access and cut manual registration checks from ten minutes to two.” This tells a recruiter what you did, how large it was, and why it mattered. When you do not have a business metric, use a concrete scale: number of users, API endpoints, test cases, screens, or teammates. Never invent a percentage to make a bullet sound finished.\n\nProjects deserve the same care as internships. Name the problem, your part, the stack, and one trade-off. Link the repository and a live demo when possible, but make sure the README explains how to run it. Recruiters may spend less than a minute on the first pass, so the project title should tell them what the product does.\n\nBefore submitting, run a final scan. Remove first-person pronouns, long paragraphs, unexplained acronyms, and old coursework that does not support the target role. Check dates for consistency and export to a text-readable PDF. Then ask someone outside your branch to tell you what they think your strongest skill is after ten seconds. If their answer matches the role, your resume is doing its job.\n\nATS compatibility is a baseline, not the finish line. Clarity, evidence, and accuracy are what make the document worth opening.`,
  },
  {
    slug: "top-10-hr-interview-questions",
    title: "Top 10 HR interview questions, with answers that do not sound rehearsed",
    excerpt: "Use a simple story structure to answer common HR questions with confidence and specificity.",
    category: "HR Interview",
    date: "2026-08-21",
    readTime: 8,
    views: 1456,
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80",
    tags: ["HR", "interviews", "storytelling"],
    content: `HR rounds are not a personality exam. They are a check for clarity, motivation, self-awareness, and the way you work with other people. The best answers sound prepared because the thinking is prepared, not because every sentence is memorised.\n\nFor “Tell me about yourself,” use the present, past, and direction. Start with what you are studying and the kind of problems you enjoy. Give one proof point from a project, internship, or responsibility. Finish with why the role is the next sensible step. Keep it under two minutes and do not recite your family history.\n\nFor “Why this company?” connect one company detail to one skill you want to use. “I noticed your team works on developer tools, and my project involved building an internal CLI. I want to learn how those tools are designed for reliability at a larger scale.” That is stronger than calling a company famous or saying you want growth.\n\nFor strengths and weaknesses, give evidence and a practice. A strength could be making unclear tasks concrete; describe the checklist you created for a team project. A weakness should be real but manageable: perhaps you used to over-polish the first solution, so now you time-box exploration and ask for feedback earlier. Avoid fake weaknesses such as perfectionism.\n\nFor conflict, failure, leadership, and pressure, use Situation, Action, Result, Learning. Keep the situation short. Spend most of the answer on what you did, what changed, and what you would repeat or change. A strong result can be a better process, not only a trophy. If your team disagreed, explain how you made the decision and kept the relationship healthy.\n\nFor “Where do you see yourself in five years?” show direction without pretending to know the exact title. Talk about the kind of responsibility you want to earn: owning a service, mentoring new teammates, or becoming strong at product thinking. Then link it to the first role.\n\nFor salary, notice period, relocation, and other practical questions, answer directly and calmly. Do not apologise for having constraints. If asked whether you have questions, ask about onboarding, success in the first six months, or how the team reviews technical decisions. Avoid asking only about leave on the first call.\n\nThe final question is often the one you ask yourself: can I be specific? Replace general adjectives with one example. A short, true story is more memorable than a flawless speech.`,
  },
  {
    slug: "aptitude-shortcuts-save-time",
    title: "Aptitude shortcuts that save time without replacing understanding",
    excerpt: "A small set of patterns for percentages, ratios, averages, and data interpretation under pressure.",
    category: "Aptitude",
    date: "2026-08-14",
    readTime: 6,
    views: 1102,
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1200&q=80",
    tags: ["aptitude", "shortcuts", "practice"],
    content: `Shortcuts are useful when they reduce repeated work. They are risky when you use them without knowing what the question is asking. The fastest aptitude solvers usually recognise a structure first, then choose the smallest calculation that proves the answer.\n\nFor percentages, remember that a percentage change is always measured against the original value. If a price rises by 20% and falls by 20%, it does not return to the starting price: the combined change is -4%. For two successive changes a and b, use a + b + ab/100, keeping the signs. This is faster and safer than inventing a convenient starting number every time.\n\nFor ratios, turn the relationship into parts. If the ratio of developers to designers is 3:2 and the total is 25, each part is 5, so the counts are 15 and 10. When a quantity changes, scale the whole ratio rather than adjusting one number. If A:B is 4:5 and A becomes 20, the multiplier is 5 and B becomes 25.\n\nFor averages, use a base. If five values are close to 50, calculate their deviations from 50 and add those deviations to 250. This helps with long lists and catches arithmetic mistakes. For weighted averages, do not average the averages unless each group has the same size. Multiply each average by its group count first.\n\nTime and work questions become clearer when you use rates. If one person finishes a job in 12 days, their rate is 1/12 per day. Combine rates, then invert the total. For pipes, speed, and production, the same idea applies. Write units beside the rate so you do not mix hours and minutes.\n\nIn data interpretation, estimate before calculating. Check the chart scale, identify the approximate answer range, and eliminate choices that cannot fit. Calculate exactly only when two options remain close. Percentages in a chart are often rounded, so a precise-looking answer may be a trap.\n\nA shortcut becomes reliable after a specific practice loop: solve ten questions normally, solve ten with the shortcut, then review every error by type. Keep a one-page formula sheet, but also write one sentence explaining when each formula does not apply. In the test, read twice, calculate once, and skip a question when the work is growing without a clear path. Time saved by leaving one trap is worth more than time saved by clever algebra.`,
  },
  {
    slug: "dsa-in-30-days",
    title: "How to prepare DSA in 30 days when you are starting late",
    excerpt: "A focused month of patterns, repetition, and review for placement coding rounds.",
    category: "DSA",
    date: "2026-08-07",
    readTime: 7,
    views: 1720,
    image: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=1200&q=80",
    tags: ["DSA", "coding", "30-day plan"],
    content: `Thirty days is not enough to solve every problem on the internet. It is enough to build a repeatable process for the patterns that appear often in placement rounds. Your goal is not a huge solved count; it is recognising a problem family, explaining your approach, and writing a correct solution under a clock.\n\nDays 1 to 5 are for arrays and strings. Practise frequency maps, prefix sums, two pointers, and sliding windows. For every problem, write the brute-force idea before the optimised one. This makes the improvement visible and gives you something to say in an interview. End each session by re-solving one problem without looking at the code.\n\nDays 6 to 10 cover stacks, queues, linked lists, and binary search. Learn the invariant behind each pattern: what remains true after every operation? For a binary search, state what your left and right boundaries mean. For a linked list, draw the pointers before changing them. A small diagram prevents many null-pointer bugs.\n\nDays 11 to 16 are trees, heaps, and greedy choices. Implement traversal from memory and practise choosing between a heap and a sorted array. Do not skip complexity analysis. A correct answer with an unexplained O(n log n) is still an incomplete interview answer.\n\nDays 17 to 22 are graphs and dynamic programming. Start with BFS and DFS, visited sets, and topological ordering. For DP, focus on state and transition rather than memorising named problems. Ask: what information from previous steps is enough to decide the current step? Begin with one-dimensional problems before moving to grids or subsequences.\n\nDays 23 to 27 are mixed sets. Take two 45-minute sessions each day: one familiar pattern and one unknown-looking problem. Practise asking clarifying questions, testing edge cases, and narrating trade-offs. Keep an error log with the exact reason you missed a problem: pattern not recognised, implementation bug, or rushed reading.\n\nDays 28 to 30 are mock rounds and review. Re-solve your five most important misses, complete two timed interviews, and write a compact pattern sheet. Sleep before the final mock. A tired brain will make your preparation look worse than it is.\n\nUse a small, consistent problem list and finish each solution with tests for empty input, one item, duplicates, and extreme values. When the month ends, keep a maintenance rhythm of three problems and one mock per week. DSA improves through recall, not through collecting tabs.`,
  },
  {
    slug: "group-discussion-mistakes",
    title: "The group discussion mistakes that quietly cost good candidates",
    excerpt: "How to contribute with structure, listening, and useful disagreement instead of trying to dominate the room.",
    category: "Group Discussion",
    date: "2026-07-31",
    readTime: 6,
    views: 834,
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=80",
    tags: ["GD", "communication", "soft skills"],
    content: `A group discussion is not won by speaking the most. Assessors are looking for people who can think clearly with others: someone who adds a useful point, makes space, handles disagreement, and helps the group reach a conclusion. Many strong students lose points by treating the room like a debate stage.\n\nThe first mistake is rushing in with an unstructured opinion. Take a few seconds to define the topic in your head. If the prompt is broad, narrow it: “I see this as a question of access, outcomes, and responsibility.” A short frame gives your next point somewhere to land. You do not need to be the first voice, but you do need to enter before the discussion has hardened.\n\nThe second mistake is repeating a point with new adjectives. Before speaking, ask whether you are adding an example, a consequence, a counterpoint, or a way forward. Use a simple structure: claim, reason, example. “Remote work can widen access because location becomes less restrictive; a hybrid model can preserve team learning for early-career employees.” One complete contribution is easier to remember than three fragments.\n\nThe third mistake is confusing interruption with confidence. If someone is speaking, listen for the end of their idea. To disagree, reference the idea rather than the person: “I agree with the concern about speed, but I see a risk in treating short-term growth as the only measure.” If another candidate keeps interrupting, do not compete for volume. Re-enter calmly: “I would like to complete this example, then I am happy to hear a different view.”\n\nThe fourth mistake is ignoring quieter members. Bringing someone in is not a performance; it improves the group’s thinking. Say, “We have discussed the employer side. I would like to hear how others see the student impact.” This shows awareness without appointing yourself chairperson.\n\nThe final mistake is ending without synthesis. If the moderator asks for a conclusion, summarise the strongest points and name the trade-off. Do not pretend the group reached agreement if it did not. A balanced close sounds mature: “We agree the change offers efficiency, while the open question is how to protect access and accountability.”\n\nPractise GDs by reviewing behaviour, not only content. After each round, note how often you spoke, whether your points were distinct, who you invited in, and how you reacted under disagreement. Content can be learned. Composure, structure, and generosity are the signals that make it easy for a recruiter to imagine you on a real team.`,
  },
];

export const resources = [
  { id: "aptitude-basics", title: "Aptitude essentials sprint", description: "A focused set of percentage, ratio, time-work, and data interpretation drills.", category: "Aptitude", level: "Starter", duration: "5 sessions", href: "/tools" },
  { id: "aptitude-timed", title: "Timed quant practice", description: "Short mixed sets that train accuracy when the clock is visible.", category: "Aptitude", level: "Intermediate", duration: "30 min", href: "/tools" },
  { id: "dsa-patterns", title: "DSA pattern map", description: "The core patterns to recognise before you start memorising solutions.", category: "DSA", level: "Starter", duration: "30 days", href: "/blog/dsa-in-30-days" },
  { id: "dsa-mocks", title: "Coding round mock pack", description: "Eight interview-style prompts with edge-case checklists and hints.", category: "DSA", level: "Intermediate", duration: "8 mocks", href: "/tools" },
  { id: "dbms-os-cn", title: "Core CS quick revision", description: "Interview-ready prompts for DBMS, operating systems, and networks.", category: "Core CS", level: "Starter", duration: "7 sessions", href: "/blog/top-10-hr-interview-questions" },
  { id: "sql-drills", title: "SQL query drills", description: "Practice joins, grouping, windows, and the explanations behind them.", category: "Core CS", level: "Intermediate", duration: "4 hours", href: "/tools" },
  { id: "resume-builder", title: "Resume proof checklist", description: "Turn project descriptions into bullets with scope, action, and outcomes.", category: "Resume", level: "Starter", duration: "20 min", href: "/tools" },
  { id: "resume-score", title: "Resume score checker", description: "Get a rule-based structure and keyword scan before you apply.", category: "Resume", level: "All levels", duration: "5 min", href: "/tools" },
  { id: "hr-stories", title: "HR story bank", description: "Prompts for teamwork, conflict, ownership, learning, and failure.", category: "HR Interview", level: "All levels", duration: "45 min", href: "/blog/top-10-hr-interview-questions" },
  { id: "mock-interview", title: "Mock interview ritual", description: "A repeatable format for practising technical and behavioural rounds.", category: "HR Interview", level: "Intermediate", duration: "60 min", href: "/tools" },
  { id: "gd-structure", title: "Group discussion structure", description: "A claim-reason-example framework for thoughtful contributions.", category: "Group Discussion", level: "Starter", duration: "30 min", href: "/blog/group-discussion-mistakes" },
  { id: "gd-topics", title: "GD topic practice list", description: "Current, balanced prompts to practise with a friend or study group.", category: "Group Discussion", level: "All levels", duration: "24 topics", href: "/tools" },
];